language: ruby
cache: bundler
rvm:
- 2.2.2
script:
- export RAILS_ENV=test
- bundle exec rake db:create db:schema:load db:test:prepare
- xvfb-run --server-args="-screen 0 1024x768x24" bundle exec rspec spec/
before_script:
- psql -c 'create database tm_test;' -U postgres
services:
- postgresql
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: FAbyVsEBjiXe7Kg71VWkikrfny3dRJxUUvBAq/2s3PFj6NJHCa7Thos9Xpyz88whauyMSpuusdgFA4c1DkVRfTI1X2vK9n24AA65S/GUG0fInjuap1MoSGxAml5hnj3YvSNoy5NzOWGTGj+bcW2Vi/Y4sKturMQO0x8MVrACEDt/3DyK5+7ut6HzoBYxuxR5Z+t2bK927aDM28BGRFqdTJKHSPRXs2NGaTaVAPxFHK2P/Bu4y2ltn1J6NuTs2s4DGJj2b1Ehb7QWLEOVKVFeIqwElO8pX52AqcJLOkchklpyQTvdg4kWRpL2c9phmxlikIdsXncqnGjHQW8GL7esCNfIQ8LbBoN7OfzCMSijbIcGLIn1ntSSwY1FHo8mcBJTLZHpXgdCChTO81z5wx5FE/hBJEHBS0VV4nnfq5kOUhjlupPOvMPaQogvyH2z9CWaxYre8YdcgZ65tqg/6e2a8AB+9caGzr07RV9JPc9in8Cqxmam9TGko2oC4fv3tU/O3OvoftWED4XDQRImoz5CyVNeT+9toTFclwUwY6J1zug0tCnRJzmqs+FSccLK3iZp9dfMGaazozEY2cWUJkO3yigkKLGFnyPAUsty6Pcm54U1FCsRirplL0z7ZyNcaYHm+HtSIKfEEL7b7fWaFER/+OtiODCRv7+LSQPTCO/8eT8=
  app: tm7
  on:
    repo: railsr/tm-assignment
